jwt:
  token:
    secret-key: ${jwt.secret}
  access:
    expiration: 31536000000 # 365일
    header: Authorization

springdoc:
  default-consumes-media-type: application/json;charset=UTF-8
  default-produces-media-type: application/json;charset=UTF-8
  swagger-ui:
    disable-swagger-default-url: true
    persistAuthorization: true
    url: /docs/index.yaml
    path: /swagger

logging:
  level:
    root: info
    com:
      amazonaws:
        util:
          EC2MetadataUtils: error

---

spring:
  profiles:
    active: dev

---

spring:
  profiles:
    active: prod